### ISSUE TITLE
Special pre-built validation rules for iterables

### ISSUE THREAD

**Issue by colonMan** [markusbohl/fluent-ts-validator#1]
Feature request: It would be nice if there were some pre-built validation rules purpose-built for iterables. 

For example:
- hasNumberOfElementsEqualTo()
- areAllDifferent()
- areAllEqual()

**Comment by markusbohl** [comment]
Thanks for your request. Yes, iterable-specific validators seem to be a useful enhancement. In a first step, I would probably go for these:

`validateIfIterable()`

- `isEmpty()`
- `isNotEmpty()`
- `hasNumberOfElements(elementCount)`
- `hasMinNumberOfElements(min)`
- `hasMaxNumberOfElements(max)`
- `hasNumberOfElementsBetween(min, max)`
- `contains(element)`
- `doesNotContain(element)`
- `containsEqualElements()`
- `containsOnlyUniqueElements()`
- `containsNoElementThatFulfills(validator | predicate)`
- `containsAtLeastOneElementThatFulfills(validator | predicate)`
- `containsOnlyElementsThatFulfill(validator | predicate)`

I'm not so sure about something like `containsOnlyEqualElements()` which would most likely represent what you probably meant with `areAllEqual()`. What kind of use case could need such a method?

**Comment by colonMan** [comment]
The suggested methods sound really good. I'm looking forward to using them. 

I can't imagine of a certain use case for `containsOnlyEqualElements()` at the moment. It's just the opposite of `containsOnlyUniqueElements() `and maybe it should be present for the sake of completeness.

**Comment by markusbohl** [comment]
Version [2.0.0](https://github.com/markusbohl/fluent-ts-validator/releases/tag/2.0.0) is out. It contains most of the methods discussed above.

Eventually, I have decided to omit the rule-building methods:
- `containsEqualElements()`
- `containsOnlyUniqueElements()`
- `containsOnlyEqualElements()`

The first two validation rules would have bad runtime complexities since a lot of comparing takes place. The third validation rule does not seem to be very relevant to me.

Of the other methods mentioned above
- `containsNoElementThatFulfills(validator | predicate)`
- `containsAtLeastOneElementThatFulfills(validator | predicate)`
- `containsOnlyElementsThatFulfill(validator | predicate)`

are omitted as well. You can apply the already existing `fulfills(validator | predicate)` method to iterables as well. Moreover, you can use the `validateIfEach...()`- methods to validate each element of a collection. I thought, it would be better to avoid some kind of redundancy here.

Tell me what you think. If the result is okay for you, I will close this issue.

**Comment by colonMan** [comment]
Very nice, thank you. This will be helpful! The issue can be closed now.
